//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageEvacuees.NSMefonimGovService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://malamteam/LoginRequest")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://malamteam/LoginResponse")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResponse", Namespace="http://malamteam/AddressResponse")]
    [System.SerializableAttribute()]
    public partial class AddressResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Address[] AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Address[] Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://malamteam/Address")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MoazaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YeshuvNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YeshuvNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Moaza {
            get {
                return this.MoazaField;
            }
            set {
                if ((this.MoazaField.Equals(value) != true)) {
                    this.MoazaField = value;
                    this.RaisePropertyChanged("Moaza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StName {
            get {
                return this.StNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StNameField, value) != true)) {
                    this.StNameField = value;
                    this.RaisePropertyChanged("StName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StNum {
            get {
                return this.StNumField;
            }
            set {
                if ((this.StNumField.Equals(value) != true)) {
                    this.StNumField = value;
                    this.RaisePropertyChanged("StNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YeshuvName {
            get {
                return this.YeshuvNameField;
            }
            set {
                if ((object.ReferenceEquals(this.YeshuvNameField, value) != true)) {
                    this.YeshuvNameField = value;
                    this.RaisePropertyChanged("YeshuvName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YeshuvNum {
            get {
                return this.YeshuvNumField;
            }
            set {
                if ((this.YeshuvNumField.Equals(value) != true)) {
                    this.YeshuvNumField = value;
                    this.RaisePropertyChanged("YeshuvNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchRequest", Namespace="http://malamteam/SearchRequest")]
    [System.SerializableAttribute()]
    public partial class SearchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMfDateOutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRowsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MefuneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MehozIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfAddHouseNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MfAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MfDateIncomeBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MfDateIncomeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfFatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MitkanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RashutIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.SortingField SortingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.SortingOrder SortingOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YeshuvNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMfDateOutcome {
            get {
                return this.IsMfDateOutcomeField;
            }
            set {
                if ((this.IsMfDateOutcomeField.Equals(value) != true)) {
                    this.IsMfDateOutcomeField = value;
                    this.RaisePropertyChanged("IsMfDateOutcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRowsPerPage {
            get {
                return this.MaxRowsPerPageField;
            }
            set {
                if ((this.MaxRowsPerPageField.Equals(value) != true)) {
                    this.MaxRowsPerPageField = value;
                    this.RaisePropertyChanged("MaxRowsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MefuneID {
            get {
                return this.MefuneIDField;
            }
            set {
                if ((this.MefuneIDField.Equals(value) != true)) {
                    this.MefuneIDField = value;
                    this.RaisePropertyChanged("MefuneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MehozId {
            get {
                return this.MehozIdField;
            }
            set {
                if ((this.MehozIdField.Equals(value) != true)) {
                    this.MehozIdField = value;
                    this.RaisePropertyChanged("MehozId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfAddHouseNum {
            get {
                return this.MfAddHouseNumField;
            }
            set {
                if ((object.ReferenceEquals(this.MfAddHouseNumField, value) != true)) {
                    this.MfAddHouseNumField = value;
                    this.RaisePropertyChanged("MfAddHouseNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MfAge {
            get {
                return this.MfAgeField;
            }
            set {
                if ((this.MfAgeField.Equals(value) != true)) {
                    this.MfAgeField = value;
                    this.RaisePropertyChanged("MfAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MfDateIncomeBegin {
            get {
                return this.MfDateIncomeBeginField;
            }
            set {
                if ((this.MfDateIncomeBeginField.Equals(value) != true)) {
                    this.MfDateIncomeBeginField = value;
                    this.RaisePropertyChanged("MfDateIncomeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MfDateIncomeEnd {
            get {
                return this.MfDateIncomeEndField;
            }
            set {
                if ((this.MfDateIncomeEndField.Equals(value) != true)) {
                    this.MfDateIncomeEndField = value;
                    this.RaisePropertyChanged("MfDateIncomeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfFather {
            get {
                return this.MfFatherField;
            }
            set {
                if ((object.ReferenceEquals(this.MfFatherField, value) != true)) {
                    this.MfFatherField = value;
                    this.RaisePropertyChanged("MfFather");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfFirstName {
            get {
                return this.MfFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MfFirstNameField, value) != true)) {
                    this.MfFirstNameField = value;
                    this.RaisePropertyChanged("MfFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfGender {
            get {
                return this.MfGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.MfGenderField, value) != true)) {
                    this.MfGenderField = value;
                    this.RaisePropertyChanged("MfGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfLastName {
            get {
                return this.MfLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MfLastNameField, value) != true)) {
                    this.MfLastNameField = value;
                    this.RaisePropertyChanged("MfLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MitkanNum {
            get {
                return this.MitkanNumField;
            }
            set {
                if ((this.MitkanNumField.Equals(value) != true)) {
                    this.MitkanNumField = value;
                    this.RaisePropertyChanged("MitkanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RashutID {
            get {
                return this.RashutIDField;
            }
            set {
                if ((this.RashutIDField.Equals(value) != true)) {
                    this.RashutIDField = value;
                    this.RaisePropertyChanged("RashutID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.SortingField SortingName {
            get {
                return this.SortingNameField;
            }
            set {
                if ((this.SortingNameField.Equals(value) != true)) {
                    this.SortingNameField = value;
                    this.RaisePropertyChanged("SortingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.SortingOrder SortingOrder {
            get {
                return this.SortingOrderField;
            }
            set {
                if ((this.SortingOrderField.Equals(value) != true)) {
                    this.SortingOrderField = value;
                    this.RaisePropertyChanged("SortingOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StNum {
            get {
                return this.StNumField;
            }
            set {
                if ((this.StNumField.Equals(value) != true)) {
                    this.StNumField = value;
                    this.RaisePropertyChanged("StNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YeshuvNum {
            get {
                return this.YeshuvNumField;
            }
            set {
                if ((this.YeshuvNumField.Equals(value) != true)) {
                    this.YeshuvNumField = value;
                    this.RaisePropertyChanged("YeshuvNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortingField", Namespace="http://schemas.datacontract.org/2004/07/Guardian.Moin.EvacueeModule.DataContract")]
    public enum SortingField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MfLastName = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MfFirstName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReshutAddress = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Address = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MfFather = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MfGender = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MfAge = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IsMfDateOutcome = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RashutName = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MitkanName = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MitkanAddress = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MitkanPhone = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortingOrder", Namespace="http://schemas.datacontract.org/2004/07/Guardian.Moin.EvacueeModule.DataContract")]
    public enum SortingOrder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESC = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResponse", Namespace="http://malamteam/SearchResponse")]
    [System.SerializableAttribute()]
    public partial class SearchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRowsPerPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.ShiltonMekomi ShiltonMekomiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRowsPerPage {
            get {
                return this.MaxRowsPerPageField;
            }
            set {
                if ((this.MaxRowsPerPageField.Equals(value) != true)) {
                    this.MaxRowsPerPageField = value;
                    this.RaisePropertyChanged("MaxRowsPerPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.ShiltonMekomi ShiltonMekomi {
            get {
                return this.ShiltonMekomiField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiltonMekomiField, value) != true)) {
                    this.ShiltonMekomiField = value;
                    this.RaisePropertyChanged("ShiltonMekomi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShiltonMekomi", Namespace="http://malamteam/ShiltonMekomi")]
    [System.SerializableAttribute()]
    public partial class ShiltonMekomi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMfDateOutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MefuneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MefuneSysNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MfAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MfDateIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfFatherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MfLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Mitkanim MitkanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiltonMekomiAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMfDateOutcome {
            get {
                return this.IsMfDateOutcomeField;
            }
            set {
                if ((this.IsMfDateOutcomeField.Equals(value) != true)) {
                    this.IsMfDateOutcomeField = value;
                    this.RaisePropertyChanged("IsMfDateOutcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MefuneID {
            get {
                return this.MefuneIDField;
            }
            set {
                if ((this.MefuneIDField.Equals(value) != true)) {
                    this.MefuneIDField = value;
                    this.RaisePropertyChanged("MefuneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MefuneSysNum {
            get {
                return this.MefuneSysNumField;
            }
            set {
                if ((this.MefuneSysNumField.Equals(value) != true)) {
                    this.MefuneSysNumField = value;
                    this.RaisePropertyChanged("MefuneSysNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MfAge {
            get {
                return this.MfAgeField;
            }
            set {
                if ((this.MfAgeField.Equals(value) != true)) {
                    this.MfAgeField = value;
                    this.RaisePropertyChanged("MfAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MfDateIncome {
            get {
                return this.MfDateIncomeField;
            }
            set {
                if ((this.MfDateIncomeField.Equals(value) != true)) {
                    this.MfDateIncomeField = value;
                    this.RaisePropertyChanged("MfDateIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfFather {
            get {
                return this.MfFatherField;
            }
            set {
                if ((object.ReferenceEquals(this.MfFatherField, value) != true)) {
                    this.MfFatherField = value;
                    this.RaisePropertyChanged("MfFather");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfFirstName {
            get {
                return this.MfFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MfFirstNameField, value) != true)) {
                    this.MfFirstNameField = value;
                    this.RaisePropertyChanged("MfFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfGender {
            get {
                return this.MfGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.MfGenderField, value) != true)) {
                    this.MfGenderField = value;
                    this.RaisePropertyChanged("MfGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MfLastName {
            get {
                return this.MfLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MfLastNameField, value) != true)) {
                    this.MfLastNameField = value;
                    this.RaisePropertyChanged("MfLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Mitkanim Mitkan {
            get {
                return this.MitkanField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanField, value) != true)) {
                    this.MitkanField = value;
                    this.RaisePropertyChanged("Mitkan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiltonMekomiAddress {
            get {
                return this.ShiltonMekomiAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiltonMekomiAddressField, value) != true)) {
                    this.ShiltonMekomiAddressField = value;
                    this.RaisePropertyChanged("ShiltonMekomiAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mitkanim", Namespace="http://malamteam/Mitkanim")]
    [System.SerializableAttribute()]
    public partial class Mitkanim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MitkanNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MitkanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.MitkanType MitkanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MitkanimAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Rashuyot RashutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MitkanName {
            get {
                return this.MitkanNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanNameField, value) != true)) {
                    this.MitkanNameField = value;
                    this.RaisePropertyChanged("MitkanName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MitkanNum {
            get {
                return this.MitkanNumField;
            }
            set {
                if ((this.MitkanNumField.Equals(value) != true)) {
                    this.MitkanNumField = value;
                    this.RaisePropertyChanged("MitkanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.MitkanType MitkanType {
            get {
                return this.MitkanTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanTypeField, value) != true)) {
                    this.MitkanTypeField = value;
                    this.RaisePropertyChanged("MitkanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MitkanimAddress {
            get {
                return this.MitkanimAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanimAddressField, value) != true)) {
                    this.MitkanimAddressField = value;
                    this.RaisePropertyChanged("MitkanimAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Rashuyot Rashut {
            get {
                return this.RashutField;
            }
            set {
                if ((object.ReferenceEquals(this.RashutField, value) != true)) {
                    this.RashutField = value;
                    this.RaisePropertyChanged("Rashut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MitkanType", Namespace="http://malamteam/Mahoz")]
    [System.SerializableAttribute()]
    public partial class MitkanType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MitkanTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MitkanTypeId {
            get {
                return this.MitkanTypeIdField;
            }
            set {
                if ((this.MitkanTypeIdField.Equals(value) != true)) {
                    this.MitkanTypeIdField = value;
                    this.RaisePropertyChanged("MitkanTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rashuyot", Namespace="http://malamteam/Rashuyot")]
    [System.SerializableAttribute()]
    public partial class Rashuyot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Mehozot MehozField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RashutIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RashutNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Mehozot Mehoz {
            get {
                return this.MehozField;
            }
            set {
                if ((object.ReferenceEquals(this.MehozField, value) != true)) {
                    this.MehozField = value;
                    this.RaisePropertyChanged("Mehoz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RashutID {
            get {
                return this.RashutIDField;
            }
            set {
                if ((this.RashutIDField.Equals(value) != true)) {
                    this.RashutIDField = value;
                    this.RaisePropertyChanged("RashutID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RashutName {
            get {
                return this.RashutNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RashutNameField, value) != true)) {
                    this.RashutNameField = value;
                    this.RaisePropertyChanged("RashutName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mehozot", Namespace="http://malamteam/Mehozot")]
    [System.SerializableAttribute()]
    public partial class Mehozot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahozNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MahozNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MahozName {
            get {
                return this.MahozNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MahozNameField, value) != true)) {
                    this.MahozNameField = value;
                    this.RaisePropertyChanged("MahozName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MahozNum {
            get {
                return this.MahozNumField;
            }
            set {
                if ((this.MahozNumField.Equals(value) != true)) {
                    this.MahozNumField = value;
                    this.RaisePropertyChanged("MahozNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchMitkanimRequest", Namespace="http://malamteam/SearchMitkanimRequest")]
    [System.SerializableAttribute()]
    public partial class SearchMitkanimRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MehozIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MitkanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RashutIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MehozId {
            get {
                return this.MehozIdField;
            }
            set {
                if ((this.MehozIdField.Equals(value) != true)) {
                    this.MehozIdField = value;
                    this.RaisePropertyChanged("MehozId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MitkanNum {
            get {
                return this.MitkanNumField;
            }
            set {
                if ((this.MitkanNumField.Equals(value) != true)) {
                    this.MitkanNumField = value;
                    this.RaisePropertyChanged("MitkanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RashutID {
            get {
                return this.RashutIDField;
            }
            set {
                if ((this.RashutIDField.Equals(value) != true)) {
                    this.RashutIDField = value;
                    this.RaisePropertyChanged("RashutID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchMitkanimResponse", Namespace="http://malamteam/SearchMitkanimResponse")]
    [System.SerializableAttribute()]
    public partial class SearchMitkanimResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MahozNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MehozIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MitkanNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MitkanNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RashutIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RashutNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sum19To65Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sum3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sum4To6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sum66Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Sum7To18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SumAllField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MahozName {
            get {
                return this.MahozNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MahozNameField, value) != true)) {
                    this.MahozNameField = value;
                    this.RaisePropertyChanged("MahozName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MehozId {
            get {
                return this.MehozIdField;
            }
            set {
                if ((this.MehozIdField.Equals(value) != true)) {
                    this.MehozIdField = value;
                    this.RaisePropertyChanged("MehozId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MitkanName {
            get {
                return this.MitkanNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanNameField, value) != true)) {
                    this.MitkanNameField = value;
                    this.RaisePropertyChanged("MitkanName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MitkanNum {
            get {
                return this.MitkanNumField;
            }
            set {
                if ((this.MitkanNumField.Equals(value) != true)) {
                    this.MitkanNumField = value;
                    this.RaisePropertyChanged("MitkanNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RashutID {
            get {
                return this.RashutIDField;
            }
            set {
                if ((this.RashutIDField.Equals(value) != true)) {
                    this.RashutIDField = value;
                    this.RaisePropertyChanged("RashutID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RashutName {
            get {
                return this.RashutNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RashutNameField, value) != true)) {
                    this.RashutNameField = value;
                    this.RaisePropertyChanged("RashutName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sum19To65 {
            get {
                return this.Sum19To65Field;
            }
            set {
                if ((this.Sum19To65Field.Equals(value) != true)) {
                    this.Sum19To65Field = value;
                    this.RaisePropertyChanged("Sum19To65");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sum3 {
            get {
                return this.Sum3Field;
            }
            set {
                if ((this.Sum3Field.Equals(value) != true)) {
                    this.Sum3Field = value;
                    this.RaisePropertyChanged("Sum3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sum4To6 {
            get {
                return this.Sum4To6Field;
            }
            set {
                if ((this.Sum4To6Field.Equals(value) != true)) {
                    this.Sum4To6Field = value;
                    this.RaisePropertyChanged("Sum4To6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sum66 {
            get {
                return this.Sum66Field;
            }
            set {
                if ((this.Sum66Field.Equals(value) != true)) {
                    this.Sum66Field = value;
                    this.RaisePropertyChanged("Sum66");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sum7To18 {
            get {
                return this.Sum7To18Field;
            }
            set {
                if ((this.Sum7To18Field.Equals(value) != true)) {
                    this.Sum7To18Field = value;
                    this.RaisePropertyChanged("Sum7To18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SumAll {
            get {
                return this.SumAllField;
            }
            set {
                if ((this.SumAllField.Equals(value) != true)) {
                    this.SumAllField = value;
                    this.RaisePropertyChanged("SumAll");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgesTypeResponse", Namespace="http://malamteam/AgesTypeResponse")]
    [System.SerializableAttribute()]
    public partial class AgesTypeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.AgeType[] AgesTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.AgeType[] AgesTypes {
            get {
                return this.AgesTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.AgesTypesField, value) != true)) {
                    this.AgesTypesField = value;
                    this.RaisePropertyChanged("AgesTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgeType", Namespace="http://malamteam/AgeType")]
    [System.SerializableAttribute()]
    public partial class AgeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeId {
            get {
                return this.AgeIdField;
            }
            set {
                if ((this.AgeIdField.Equals(value) != true)) {
                    this.AgeIdField = value;
                    this.RaisePropertyChanged("AgeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgeName {
            get {
                return this.AgeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeNameField, value) != true)) {
                    this.AgeNameField = value;
                    this.RaisePropertyChanged("AgeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RashuyotResponse", Namespace="http://malamteam/RashuyotResponse")]
    [System.SerializableAttribute()]
    public partial class RashuyotResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Rashuyot[] RashuyotField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Rashuyot[] Rashuyot {
            get {
                return this.RashuyotField;
            }
            set {
                if ((object.ReferenceEquals(this.RashuyotField, value) != true)) {
                    this.RashuyotField = value;
                    this.RaisePropertyChanged("Rashuyot");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YeshuvimResponse", Namespace="http://malamteam/YeshuvimResponse")]
    [System.SerializableAttribute()]
    public partial class YeshuvimResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Yeshuvim[] YeshuvimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Yeshuvim[] Yeshuvim {
            get {
                return this.YeshuvimField;
            }
            set {
                if ((object.ReferenceEquals(this.YeshuvimField, value) != true)) {
                    this.YeshuvimField = value;
                    this.RaisePropertyChanged("Yeshuvim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yeshuvim", Namespace="http://malamteam/Yeshuvim")]
    [System.SerializableAttribute()]
    public partial class Yeshuvim : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Mehozot MehozField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YeshuvNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YeshuvNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Mehozot Mehoz {
            get {
                return this.MehozField;
            }
            set {
                if ((object.ReferenceEquals(this.MehozField, value) != true)) {
                    this.MehozField = value;
                    this.RaisePropertyChanged("Mehoz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YeshuvName {
            get {
                return this.YeshuvNameField;
            }
            set {
                if ((object.ReferenceEquals(this.YeshuvNameField, value) != true)) {
                    this.YeshuvNameField = value;
                    this.RaisePropertyChanged("YeshuvName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YeshuvNum {
            get {
                return this.YeshuvNumField;
            }
            set {
                if ((this.YeshuvNumField.Equals(value) != true)) {
                    this.YeshuvNumField = value;
                    this.RaisePropertyChanged("YeshuvNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MitkanimResponse", Namespace="http://malamteam/RashuyotResponse")]
    [System.SerializableAttribute()]
    public partial class MitkanimResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ManageEvacuees.NSMefonimGovService.Mitkanim[] MitkanimField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsError {
            get {
                return this.IsErrorField;
            }
            set {
                if ((this.IsErrorField.Equals(value) != true)) {
                    this.IsErrorField = value;
                    this.RaisePropertyChanged("IsError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ManageEvacuees.NSMefonimGovService.Mitkanim[] Mitkanim {
            get {
                return this.MitkanimField;
            }
            set {
                if ((object.ReferenceEquals(this.MitkanimField, value) != true)) {
                    this.MitkanimField = value;
                    this.RaisePropertyChanged("Mitkanim");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://malamteam/IMefonimGovService", ConfigurationName="NSMefonimGovService.IMefonimGovService")]
    public interface IMefonimGovService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/Ping", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/PingResponse")]
        string Ping(string s);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/Login", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/LoginResponse")]
        ManageEvacuees.NSMefonimGovService.LoginResponse Login(ManageEvacuees.NSMefonimGovService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/GetAddress", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/GetAddressResponse")]
        ManageEvacuees.NSMefonimGovService.AddressResponse GetAddress();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/Search", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/SearchResponse")]
        ManageEvacuees.NSMefonimGovService.SearchResponse Search(ManageEvacuees.NSMefonimGovService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/SearchMitkanim", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/SearchMitkanimResponse")]
        ManageEvacuees.NSMefonimGovService.SearchMitkanimResponse SearchMitkanim(ManageEvacuees.NSMefonimGovService.SearchMitkanimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/GetAgesType", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/GetAgesTypeResponse")]
        ManageEvacuees.NSMefonimGovService.AgesTypeResponse GetAgesType();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/GetRashuyot", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/GetRashuyotResponse")]
        ManageEvacuees.NSMefonimGovService.RashuyotResponse GetRashuyot();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/GetYeshuvim", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/GetYeshuvimResponse")]
        ManageEvacuees.NSMefonimGovService.YeshuvimResponse GetYeshuvim();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://malamteam/IMefonimGovService/IMefonimGovService/GetMitkanim", ReplyAction="http://malamteam/IMefonimGovService/IMefonimGovService/GetMitkanimResponse")]
        ManageEvacuees.NSMefonimGovService.MitkanimResponse GetMitkanim();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMefonimGovServiceChannel : ManageEvacuees.NSMefonimGovService.IMefonimGovService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MefonimGovServiceClient : System.ServiceModel.ClientBase<ManageEvacuees.NSMefonimGovService.IMefonimGovService>, ManageEvacuees.NSMefonimGovService.IMefonimGovService {
        
        public MefonimGovServiceClient() {
        }
        
        public MefonimGovServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MefonimGovServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MefonimGovServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MefonimGovServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string s) {
            return base.Channel.Ping(s);
        }
        
        public ManageEvacuees.NSMefonimGovService.LoginResponse Login(ManageEvacuees.NSMefonimGovService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ManageEvacuees.NSMefonimGovService.AddressResponse GetAddress() {
            return base.Channel.GetAddress();
        }
        
        public ManageEvacuees.NSMefonimGovService.SearchResponse Search(ManageEvacuees.NSMefonimGovService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public ManageEvacuees.NSMefonimGovService.SearchMitkanimResponse SearchMitkanim(ManageEvacuees.NSMefonimGovService.SearchMitkanimRequest request) {
            return base.Channel.SearchMitkanim(request);
        }
        
        public ManageEvacuees.NSMefonimGovService.AgesTypeResponse GetAgesType() {
            return base.Channel.GetAgesType();
        }
        
        public ManageEvacuees.NSMefonimGovService.RashuyotResponse GetRashuyot() {
            return base.Channel.GetRashuyot();
        }
        
        public ManageEvacuees.NSMefonimGovService.YeshuvimResponse GetYeshuvim() {
            return base.Channel.GetYeshuvim();
        }
        
        public ManageEvacuees.NSMefonimGovService.MitkanimResponse GetMitkanim() {
            return base.Channel.GetMitkanim();
        }
    }
}
