#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoinLocalGovDataService.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShiltomMekomi")]
	public partial class DocumentsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DocumentsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShiltomMekomiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DocumentsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetPortalDocumentsTypesInsp")]
		public ISingleResult<LGSite_GetPortalDocumentsTypesInspResult> GetDocumentsTypesInsp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LGSite_GetPortalDocumentsTypesInspResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetReportDocumentsInsp")]
		public ISingleResult<LGSite_GetReportDocumentsInspResult> GetDocumentsInspection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocActivity", DbType="Int")] System.Nullable<int> docActivity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromRow", DbType="Int")] System.Nullable<int> fromRow, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToRow", DbType="Int")] System.Nullable<int> toRow)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), year, docActivity, fromRow, toRow);
			return ((ISingleResult<LGSite_GetReportDocumentsInspResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetPortalDocumentContent")]
		public ISingleResult<LGSite_GetPortalDocumentContentResult> GetDocumentContent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocID", DbType="Int")] System.Nullable<int> docID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), docID);
			return ((ISingleResult<LGSite_GetPortalDocumentContentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetReportDocumentsElection")]
		public ISingleResult<LGSite_GetReportDocumentsElectionResult> GetDocumentsElection([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromRow", DbType="Int")] System.Nullable<int> fromRow, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToRow", DbType="Int")] System.Nullable<int> toRow, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fromRow, toRow, fromDate, toDate);
			return ((ISingleResult<LGSite_GetReportDocumentsElectionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetPortalDocumentsTypes")]
		public ISingleResult<LGSite_GetPortalDocumentsTypesResult> GetPortalDocumentsTypes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LGSite_GetPortalDocumentsTypesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetReportDocumentsRashut")]
		public ISingleResult<LGSite_GetReportDocumentsRashutResult> GetReportDocumentsRashut([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_DocActivity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_RashutNumLms, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromRow", DbType="Int")] System.Nullable<int> fromRow, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToRow", DbType="Int")] System.Nullable<int> toRow)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_DocActivity, p_RashutNumLms, fromRow, toRow);
			return ((ISingleResult<LGSite_GetReportDocumentsRashutResult>)(result.ReturnValue));
		}
	}
	
	public partial class LGSite_GetPortalDocumentsTypesInspResult
	{
		
		private int _DocTypeID;
		
		private string _DocTypeName;
		
		public LGSite_GetPortalDocumentsTypesInspResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeID", DbType="Int NOT NULL")]
		public int DocTypeID
		{
			get
			{
				return this._DocTypeID;
			}
			set
			{
				if ((this._DocTypeID != value))
				{
					this._DocTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocTypeName
		{
			get
			{
				return this._DocTypeName;
			}
			set
			{
				if ((this._DocTypeName != value))
				{
					this._DocTypeName = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetReportDocumentsInspResult
	{
		
		private System.Nullable<int> _totalRows;
		
		private System.Nullable<long> _rownum;
		
		private string _Shem_Rashut;
		
		private string _DocTypeName;
		
		private string _DocName;
		
		private int _DocId;
		
		public LGSite_GetReportDocumentsInspResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRows", DbType="Int")]
		public System.Nullable<int> totalRows
		{
			get
			{
				return this._totalRows;
			}
			set
			{
				if ((this._totalRows != value))
				{
					this._totalRows = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rownum", DbType="BigInt")]
		public System.Nullable<long> rownum
		{
			get
			{
				return this._rownum;
			}
			set
			{
				if ((this._rownum != value))
				{
					this._rownum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shem_Rashut", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Shem_Rashut
		{
			get
			{
				return this._Shem_Rashut;
			}
			set
			{
				if ((this._Shem_Rashut != value))
				{
					this._Shem_Rashut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocTypeName
		{
			get
			{
				return this._DocTypeName;
			}
			set
			{
				if ((this._DocTypeName != value))
				{
					this._DocTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DocName
		{
			get
			{
				return this._DocName;
			}
			set
			{
				if ((this._DocName != value))
				{
					this._DocName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocId", DbType="Int NOT NULL")]
		public int DocId
		{
			get
			{
				return this._DocId;
			}
			set
			{
				if ((this._DocId != value))
				{
					this._DocId = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetPortalDocumentContentResult
	{
		
		private System.Data.Linq.Binary _DocPath;
		
		private string _DocExtention;
		
		public LGSite_GetPortalDocumentContentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocPath", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary DocPath
		{
			get
			{
				return this._DocPath;
			}
			set
			{
				if ((this._DocPath != value))
				{
					this._DocPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocExtention", DbType="VarChar(50)")]
		public string DocExtention
		{
			get
			{
				return this._DocExtention;
			}
			set
			{
				if ((this._DocExtention != value))
				{
					this._DocExtention = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetReportDocumentsElectionResult
	{
		
		private System.Nullable<int> _totalRows;
		
		private System.Nullable<long> _rownum;
		
		private string _Shem_Rashut;
		
		private string _DocTypeName;
		
		private string _DocName;
		
		private int _DocId;
		
		private System.DateTime _AcceptDate;
		
		private int _DocYear;
		
		public LGSite_GetReportDocumentsElectionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRows", DbType="Int")]
		public System.Nullable<int> totalRows
		{
			get
			{
				return this._totalRows;
			}
			set
			{
				if ((this._totalRows != value))
				{
					this._totalRows = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rownum", DbType="BigInt")]
		public System.Nullable<long> rownum
		{
			get
			{
				return this._rownum;
			}
			set
			{
				if ((this._rownum != value))
				{
					this._rownum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shem_Rashut", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Shem_Rashut
		{
			get
			{
				return this._Shem_Rashut;
			}
			set
			{
				if ((this._Shem_Rashut != value))
				{
					this._Shem_Rashut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocTypeName
		{
			get
			{
				return this._DocTypeName;
			}
			set
			{
				if ((this._DocTypeName != value))
				{
					this._DocTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DocName
		{
			get
			{
				return this._DocName;
			}
			set
			{
				if ((this._DocName != value))
				{
					this._DocName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocId", DbType="Int NOT NULL")]
		public int DocId
		{
			get
			{
				return this._DocId;
			}
			set
			{
				if ((this._DocId != value))
				{
					this._DocId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptDate", DbType="DateTime NOT NULL")]
		public System.DateTime AcceptDate
		{
			get
			{
				return this._AcceptDate;
			}
			set
			{
				if ((this._AcceptDate != value))
				{
					this._AcceptDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocYear", DbType="Int NOT NULL")]
		public int DocYear
		{
			get
			{
				return this._DocYear;
			}
			set
			{
				if ((this._DocYear != value))
				{
					this._DocYear = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetPortalDocumentsTypesResult
	{
		
		private int _DocMainTypeID;
		
		private string _DocMainTypeName;
		
		private short _SysNo;
		
		public LGSite_GetPortalDocumentsTypesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocMainTypeID", DbType="Int NOT NULL")]
		public int DocMainTypeID
		{
			get
			{
				return this._DocMainTypeID;
			}
			set
			{
				if ((this._DocMainTypeID != value))
				{
					this._DocMainTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocMainTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocMainTypeName
		{
			get
			{
				return this._DocMainTypeName;
			}
			set
			{
				if ((this._DocMainTypeName != value))
				{
					this._DocMainTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysNo", DbType="SmallInt NOT NULL")]
		public short SysNo
		{
			get
			{
				return this._SysNo;
			}
			set
			{
				if ((this._SysNo != value))
				{
					this._SysNo = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetReportDocumentsRashutResult
	{
		
		private System.Nullable<int> _totalRows;
		
		private System.Nullable<long> _rownum;
		
		private int _DocYear;
		
		private string _DocName;
		
		private int _DocId;
		
		private System.DateTime _AcceptDate;
		
		private string _DocTypeName;
		
		public LGSite_GetReportDocumentsRashutResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRows", DbType="Int")]
		public System.Nullable<int> totalRows
		{
			get
			{
				return this._totalRows;
			}
			set
			{
				if ((this._totalRows != value))
				{
					this._totalRows = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rownum", DbType="BigInt")]
		public System.Nullable<long> rownum
		{
			get
			{
				return this._rownum;
			}
			set
			{
				if ((this._rownum != value))
				{
					this._rownum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocYear", DbType="Int NOT NULL")]
		public int DocYear
		{
			get
			{
				return this._DocYear;
			}
			set
			{
				if ((this._DocYear != value))
				{
					this._DocYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DocName
		{
			get
			{
				return this._DocName;
			}
			set
			{
				if ((this._DocName != value))
				{
					this._DocName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocId", DbType="Int NOT NULL")]
		public int DocId
		{
			get
			{
				return this._DocId;
			}
			set
			{
				if ((this._DocId != value))
				{
					this._DocId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptDate", DbType="DateTime NOT NULL")]
		public System.DateTime AcceptDate
		{
			get
			{
				return this._AcceptDate;
			}
			set
			{
				if ((this._AcceptDate != value))
				{
					this._AcceptDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DocTypeName
		{
			get
			{
				return this._DocTypeName;
			}
			set
			{
				if ((this._DocTypeName != value))
				{
					this._DocTypeName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
