#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoinLocalGovDataService.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShiltomMekomi")]
	public partial class LawSubjectsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LawSubjectsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShiltomMekomiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LawSubjectsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LawSubjectsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LawSubjectsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LawSubjectsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetLawSubjects")]
		public ISingleResult<LGSite_GetLawSubjectsResult> GetLawSubjects()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LGSite_GetLawSubjectsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetPortalLaws")]
		public ISingleResult<LGSite_GetPortalLawsResult> GetLaws([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectID", DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rashut_Lms", DbType="Int")] System.Nullable<int> rashut_Lms, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromRow", DbType="Int")] System.Nullable<int> fromRow, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToRow", DbType="Int")] System.Nullable<int> toRow)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectID, rashut_Lms, fromRow, toRow);
			return ((ISingleResult<LGSite_GetPortalLawsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetPortalLawContent")]
		public ISingleResult<LGSite_GetPortalLawContentResult> GetLawContent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LawID", DbType="Int")] System.Nullable<int> lawID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lawID);
			return ((ISingleResult<LGSite_GetPortalLawContentResult>)(result.ReturnValue));
		}
	}
	
	public partial class LGSite_GetLawSubjectsResult
	{
		
		private int _SubjectID;
		
		private string _SubjectName;
		
		public LGSite_GetLawSubjectsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetPortalLawsResult
	{
		
		private System.Nullable<int> _totalRows;
		
		private System.Nullable<long> _rownum;
		
		private int _LawID;
		
		private string _LawName;
		
		private System.DateTime _DateRecord;
		
		private int _SubjectID;
		
		private string _SubjectName;
		
		private int _RashutNumLms;
		
		private string _Shem_Rashut;
		
		public LGSite_GetPortalLawsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRows", DbType="Int")]
		public System.Nullable<int> totalRows
		{
			get
			{
				return this._totalRows;
			}
			set
			{
				if ((this._totalRows != value))
				{
					this._totalRows = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rownum", DbType="BigInt")]
		public System.Nullable<long> rownum
		{
			get
			{
				return this._rownum;
			}
			set
			{
				if ((this._rownum != value))
				{
					this._rownum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LawID", DbType="Int NOT NULL")]
		public int LawID
		{
			get
			{
				return this._LawID;
			}
			set
			{
				if ((this._LawID != value))
				{
					this._LawID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LawName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string LawName
		{
			get
			{
				return this._LawName;
			}
			set
			{
				if ((this._LawName != value))
				{
					this._LawName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRecord", DbType="DateTime NOT NULL")]
		public System.DateTime DateRecord
		{
			get
			{
				return this._DateRecord;
			}
			set
			{
				if ((this._DateRecord != value))
				{
					this._DateRecord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string SubjectName
		{
			get
			{
				return this._SubjectName;
			}
			set
			{
				if ((this._SubjectName != value))
				{
					this._SubjectName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RashutNumLms", DbType="Int NOT NULL")]
		public int RashutNumLms
		{
			get
			{
				return this._RashutNumLms;
			}
			set
			{
				if ((this._RashutNumLms != value))
				{
					this._RashutNumLms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shem_Rashut", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Shem_Rashut
		{
			get
			{
				return this._Shem_Rashut;
			}
			set
			{
				if ((this._Shem_Rashut != value))
				{
					this._Shem_Rashut = value;
				}
			}
		}
	}
	
	public partial class LGSite_GetPortalLawContentResult
	{
		
		private System.Data.Linq.Binary _Content;
		
		private string _Extention;
		
		public LGSite_GetPortalLawContentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extention", DbType="VarChar(10)")]
		public string Extention
		{
			get
			{
				return this._Extention;
			}
			set
			{
				if ((this._Extention != value))
				{
					this._Extention = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
