#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoinLocalGovDataService.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShiltomMekomi")]
	public partial class MeafyenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MeafyenDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShiltomMekomiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MeafyenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeafyenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeafyenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeafyenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetRashutMeafyenim")]
		public ISingleResult<LGSite_GetRashutMeafyenimResult> GetRashutMeafyenim([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> numrashut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numrashut);
			return ((ISingleResult<LGSite_GetRashutMeafyenimResult>)(result.ReturnValue));
		}
	}
	
	public partial class LGSite_GetRashutMeafyenimResult
	{
		
		private System.Nullable<int> _NumMeafyen;
		
		private System.Nullable<int> _ValueId;
		
		private string _StringValue;
		
		private System.Nullable<System.DateTime> _DateValue;
		
		private System.Nullable<int> _NumericValue;
		
		private string _NameMeafyen;
		
		private System.Nullable<int> _TypeMeafyen;
		
		private System.Nullable<int> _IsSelection;
		
		private string _ValueName;
		
		private string _Shem_Rashut;
		
		public LGSite_GetRashutMeafyenimResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumMeafyen", DbType="Int")]
		public System.Nullable<int> NumMeafyen
		{
			get
			{
				return this._NumMeafyen;
			}
			set
			{
				if ((this._NumMeafyen != value))
				{
					this._NumMeafyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueId", DbType="Int")]
		public System.Nullable<int> ValueId
		{
			get
			{
				return this._ValueId;
			}
			set
			{
				if ((this._ValueId != value))
				{
					this._ValueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringValue", DbType="NVarChar(255)")]
		public string StringValue
		{
			get
			{
				return this._StringValue;
			}
			set
			{
				if ((this._StringValue != value))
				{
					this._StringValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateValue", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateValue
		{
			get
			{
				return this._DateValue;
			}
			set
			{
				if ((this._DateValue != value))
				{
					this._DateValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumericValue", DbType="Int")]
		public System.Nullable<int> NumericValue
		{
			get
			{
				return this._NumericValue;
			}
			set
			{
				if ((this._NumericValue != value))
				{
					this._NumericValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameMeafyen", DbType="NVarChar(1000)")]
		public string NameMeafyen
		{
			get
			{
				return this._NameMeafyen;
			}
			set
			{
				if ((this._NameMeafyen != value))
				{
					this._NameMeafyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeMeafyen", DbType="Int")]
		public System.Nullable<int> TypeMeafyen
		{
			get
			{
				return this._TypeMeafyen;
			}
			set
			{
				if ((this._TypeMeafyen != value))
				{
					this._TypeMeafyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSelection", DbType="Int")]
		public System.Nullable<int> IsSelection
		{
			get
			{
				return this._IsSelection;
			}
			set
			{
				if ((this._IsSelection != value))
				{
					this._IsSelection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValueName", DbType="NVarChar(255)")]
		public string ValueName
		{
			get
			{
				return this._ValueName;
			}
			set
			{
				if ((this._ValueName != value))
				{
					this._ValueName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shem_Rashut", DbType="VarChar(50)")]
		public string Shem_Rashut
		{
			get
			{
				return this._Shem_Rashut;
			}
			set
			{
				if ((this._Shem_Rashut != value))
				{
					this._Shem_Rashut = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
