#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoinLocalGovDataService.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShiltonMekomi")]
	public partial class RashutDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RashutDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ShiltomMekomiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RashutDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RashutDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RashutDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RashutDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LGSite_GetRashuyot")]
		public ISingleResult<LGSite_GetRashuyotResult> GetRashuyot()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LGSite_GetRashuyotResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GLOBAL_GetRelatedEntitiesForRashut")]
		public ISingleResult<GLOBAL_GetRelatedEntitiesForRashutResult> GLOBAL_GetRelatedEntitiesForRashut([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RashutID", DbType="Int")] System.Nullable<int> rashutID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromRow", DbType="Int")] System.Nullable<int> fromRow, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToRow", DbType="Int")] System.Nullable<int> toRow)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rashutID, fromRow, toRow);
			return ((ISingleResult<GLOBAL_GetRelatedEntitiesForRashutResult>)(result.ReturnValue));
		}
	}
	
	public partial class LGSite_GetRashuyotResult
	{
		
		private int _Kod_Rashut_Lms;
		
		private string _Shem_Rashut;
		
		public LGSite_GetRashuyotResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod_Rashut_Lms", DbType="Int NOT NULL")]
		public int Kod_Rashut_Lms
		{
			get
			{
				return this._Kod_Rashut_Lms;
			}
			set
			{
				if ((this._Kod_Rashut_Lms != value))
				{
					this._Kod_Rashut_Lms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shem_Rashut", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Shem_Rashut
		{
			get
			{
				return this._Shem_Rashut;
			}
			set
			{
				if ((this._Shem_Rashut != value))
				{
					this._Shem_Rashut = value;
				}
			}
		}
	}
	
	public partial class GLOBAL_GetRelatedEntitiesForRashutResult
	{
		
		private System.Nullable<int> _totalRows;
		
		private System.Nullable<long> _rownum;
		
		private int _RelatedEntityID;
		
		private string _MainTypeName;
		
		private string _SubTypeName;
		
		private System.Nullable<int> _MainTypeID;
		
		private int _SubTypeID;
		
		private string _RelatedEntityName;
		
		private System.DateTime _DateStart;
		
		private System.Nullable<System.DateTime> _DateEnd;
		
		private int _Participating;
		
		private bool _Active;
		
		public GLOBAL_GetRelatedEntitiesForRashutResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRows", DbType="Int")]
		public System.Nullable<int> totalRows
		{
			get
			{
				return this._totalRows;
			}
			set
			{
				if ((this._totalRows != value))
				{
					this._totalRows = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rownum", DbType="BigInt")]
		public System.Nullable<long> rownum
		{
			get
			{
				return this._rownum;
			}
			set
			{
				if ((this._rownum != value))
				{
					this._rownum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedEntityID", DbType="Int NOT NULL")]
		public int RelatedEntityID
		{
			get
			{
				return this._RelatedEntityID;
			}
			set
			{
				if ((this._RelatedEntityID != value))
				{
					this._RelatedEntityID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainTypeName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string MainTypeName
		{
			get
			{
				return this._MainTypeName;
			}
			set
			{
				if ((this._MainTypeName != value))
				{
					this._MainTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTypeName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string SubTypeName
		{
			get
			{
				return this._SubTypeName;
			}
			set
			{
				if ((this._SubTypeName != value))
				{
					this._SubTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainTypeID", DbType="Int")]
		public System.Nullable<int> MainTypeID
		{
			get
			{
				return this._MainTypeID;
			}
			set
			{
				if ((this._MainTypeID != value))
				{
					this._MainTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTypeID", DbType="Int NOT NULL")]
		public int SubTypeID
		{
			get
			{
				return this._SubTypeID;
			}
			set
			{
				if ((this._SubTypeID != value))
				{
					this._SubTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedEntityName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string RelatedEntityName
		{
			get
			{
				return this._RelatedEntityName;
			}
			set
			{
				if ((this._RelatedEntityName != value))
				{
					this._RelatedEntityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateStart", DbType="DateTime NOT NULL")]
		public System.DateTime DateStart
		{
			get
			{
				return this._DateStart;
			}
			set
			{
				if ((this._DateStart != value))
				{
					this._DateStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEnd
		{
			get
			{
				return this._DateEnd;
			}
			set
			{
				if ((this._DateEnd != value))
				{
					this._DateEnd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Participating", DbType="Int NOT NULL")]
		public int Participating
		{
			get
			{
				return this._Participating;
			}
			set
			{
				if ((this._Participating != value))
				{
					this._Participating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
